/* ===========================================================
   Coffee J — menu data
   Transcribed from the shop's own menu PDF (Coffee J Menu).
   Prices are rupiah. Printed menu lists them in thousands,
   e.g. "KOPI JADOEL 10" = Rp 10.000.

   `photo` refers to images/dishes/NN.jpg, numbered from the
   raw photo set. Items without a photo render a plain row.
   =========================================================== */

window.CJ_CATEGORIES = [
  { id: 'breakfast', label: 'Breakfast',     note: 'Disajikan dari jam 06.30' },
  { id: 'snacks',    label: 'Snacks' },
  { id: 'lauk',      label: 'Lauk' },
  { id: 'sayur',     label: 'Sayur' },
  { id: 'soup',      label: 'Soup' },
  { id: 'nasi',      label: 'Nasi' },
  { id: 'mie',       label: 'Mie' },
  { id: 'nasgor',    label: 'Nasi Goreng' },
  { id: 'coffee',    label: 'Kopi' },
  { id: 'modern',    label: 'Modern Coffee' },
  { id: 'tea',       label: 'Teh' },
  { id: 'icecream',  label: 'Ice Cream' },
  { id: 'soda',      label: 'Soda' },
  { id: 'juice',     label: 'Jus' },
  { id: 'noncoffee', label: 'Non-Coffee' },
  { id: 'magnum',    label: 'Magnum' },
];

/* id, cat, name, price, optional: desc, photo, tag, focus
   focus sets object-position inside the circular frame, e.g. '50% 68%'
   pulls the crop downward when the dish sits low in the photo. */
window.CJ_MENU = [
  /* ---------------- BREAKFAST ---------------- */
  { id: 'telur-kampung',      cat: 'breakfast', name: 'Telur Ayam Kampung 1/2 Matang', price: 16000, desc: 'Telur ayam kampung rebus setengah matang' },
  { id: 'bubur-ayam-kampung', cat: 'breakfast', name: 'Bubur Ayam Kampung', price: 30000, desc: 'Bubur nasi dengan suwiran ayam kampung', photo: '13' },
  { id: 'bubur-ayam-special', cat: 'breakfast', name: 'Bubur Ayam Special', price: 30000, desc: 'Bubur ayam lengkap dengan aneka pelengkap', photo: '24', tag: 'Favorit' },
  { id: 'bubur-ikan',         cat: 'breakfast', name: 'Bubur Ikan', price: 30000, desc: 'Bubur nasi dengan potongan ikan', photo: '55' },
  { id: 'bubur-ikan-hokian',  cat: 'breakfast', name: 'Bubur Ikan Hokian', price: 38000, desc: 'Bubur ikan gaya Hokian, kuahnya lebih gurih' },
  { id: 'mie-ayam-suwir',     cat: 'breakfast', name: 'Mie Ayam Kampung Suwir', price: 32000, desc: 'Mie dengan suwiran ayam kampung', photo: '46' },
  { id: 'mie-ayam-cincang',   cat: 'breakfast', name: 'Mie Ayam Daging Cincang', price: 30000, desc: 'Mie dengan daging ayam cincang' },
  { id: 'mie-ayam-chasiu',    cat: 'breakfast', name: 'Mie Ayam Chasiu', price: 30000, desc: 'Mie dengan irisan daging chasiu manis' },
  { id: 'bihun-ayam-chasiu',  cat: 'breakfast', name: 'Bihun Ayam Chasiu', price: 28000, desc: 'Bihun dengan irisan daging chasiu' },
  { id: 'bihun-ayam-cincang', cat: 'breakfast', name: 'Bihun Ayam Cincang', price: 28000, desc: 'Bihun dengan daging ayam cincang' },
  { id: 'bihun-ayam-suwir',   cat: 'breakfast', name: 'Bihun Ayam Kampung Suwir', price: 30000, desc: 'Bihun dengan suwiran ayam kampung' },
  { id: 'misua-ayam-suwir',   cat: 'breakfast', name: 'Misua Ayam Kampung Suwir', price: 35000, desc: 'Mi misua halus dengan suwiran ayam kampung', photo: '03' },
  { id: 'misua-ayam-cincang', cat: 'breakfast', name: 'Misua Ayam Cincang', price: 33000, desc: 'Mi misua halus dengan ayam cincang' },
  { id: 'kwetiau-goreng-sapi-bf', cat: 'breakfast', name: 'Kwetiau Goreng Sapi', price: 48000, desc: 'Kwetiau goreng dengan irisan daging sapi' },
  { id: 'lontong-sayur',      cat: 'breakfast', name: 'Lontong Sayur', price: 20000, desc: 'Lontong dengan kuah sayur bersantan' },
  { id: 'lontong-komplit',    cat: 'breakfast', name: 'Lontong Komplit', price: 26000, desc: 'Lontong sayur dengan telur dan pelengkap' },
  { id: 'lontong-special',    cat: 'breakfast', name: 'Lontong Special', price: 42000, desc: 'Lontong sayur porsi lengkap dengan aneka lauk' },
  { id: 'mie-celor',          cat: 'breakfast', name: 'Mie Celor', price: 28000, desc: 'Mi kuah santan udang dengan telur, khas Palembang', photo: '07', focus: '50% 68%', tag: 'Khas Palembang' },
  { id: 'laksan',             cat: 'breakfast', name: 'Laksan', price: 8000, desc: 'Pempek disiram kuah santan, khas Palembang' },
  { id: 'lakso',              cat: 'breakfast', name: 'Lakso', price: 12000, desc: 'Mi beras dengan kuah santan kuning' },
  { id: 'burgo',              cat: 'breakfast', name: 'Burgo', price: 12000, desc: 'Lembaran tepung beras digulung, kuah santan' },
  { id: 'celimpungan',        cat: 'breakfast', name: 'Celimpungan (isi 3)', price: 16000, desc: 'Bola ikan disiram kuah santan gurih' },
  { id: 'topping-bakso-sapi', cat: 'breakfast', name: 'Topping — Bakso Sapi', price: 10000, desc: 'Tambahan bakso sapi' },
  { id: 'topping-bakso-ayam', cat: 'breakfast', name: 'Topping — Bakso Ayam', price: 10000, desc: 'Tambahan bakso ayam' },

  /* ---------------- SNACKS ---------------- */
  { id: 'pisang-jadoel',      cat: 'snacks', name: 'Pisang Goreng Jadoel', price: 20000, desc: 'Pisang goreng klasik, tanpa topping' },
  { id: 'pisang-keju-susu',   cat: 'snacks', name: 'Pisang Goreng Keju Susu', price: 24000, desc: 'Pisang goreng dengan keju parut dan susu kental' },
  { id: 'pisang-coklat-susu', cat: 'snacks', name: 'Pisang Goreng Coklat Susu', price: 24000, desc: 'Pisang goreng dengan coklat dan susu kental' },
  { id: 'pisang-coklat-keju', cat: 'snacks', name: 'Pisang Goreng Coklat Keju', price: 26000, desc: 'Pisang goreng dengan coklat dan keju' },
  { id: 'ubi-jepang',         cat: 'snacks', name: 'Ubi ala Jepang', price: 26000, desc: 'Ubi manis panggang ala Jepang' },
  { id: 'siomay-ayam',        cat: 'snacks', name: 'Siomay Ayam', price: 25000, desc: 'Siomay kukus isi ayam', photo: '05' },
  { id: 'siomay-rumput-laut', cat: 'snacks', name: 'Siomay Rumput Laut', price: 25000, desc: 'Siomay kukus dengan rumput laut' },
  { id: 'ekado-kepiting',     cat: 'snacks', name: 'Ekado Kepiting', price: 25000, desc: 'Ekado goreng isi kepiting' },
  { id: 'lumpiah-seafood',    cat: 'snacks', name: 'Lumpiah Seafood', price: 25000, desc: 'Lumpia goreng isi seafood' },
  { id: 'mantao-original',    cat: 'snacks', name: 'Mantao Original (isi 3)', price: 28000, desc: 'Roti mantao kukus, enak dicocol susu kental', photo: '60', tag: 'Favorit' },
  { id: 'bakpao-ayam-merah',  cat: 'snacks', name: 'Bakpao Ayam Merah (isi 3)', price: 28000, desc: 'Bakpao kukus isi ayam bumbu merah', photo: '50' },
  { id: 'roti-bakar-jadoel',  cat: 'snacks', name: 'Roti Bakar Gandum — Jadoel', price: 20000, desc: 'Roti gandum bakar klasik, tanpa topping' },
  { id: 'roti-bakar-coklat-susu', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Susu', price: 24000, desc: 'Roti gandum bakar, coklat dan susu kental' },
  { id: 'roti-bakar-keju-susu',   cat: 'snacks', name: 'Roti Bakar Gandum — Keju Susu', price: 24000, desc: 'Roti gandum bakar, keju dan susu kental' },
  { id: 'roti-bakar-coklat-keju', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Keju', price: 25000, desc: 'Roti gandum bakar, coklat dan keju parut', tag: 'Bestseller' },
  { id: 'roti-bakar-kacang',      cat: 'snacks', name: 'Roti Bakar Gandum — Kacang', price: 28000, desc: 'Roti gandum bakar dengan selai kacang' },
  { id: 'roti-bakar-coklat-kacang', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Kacang', price: 28000, desc: 'Roti gandum bakar, coklat dan kacang' },
  { id: 'roti-bakar-kaya',    cat: 'snacks', name: 'Roti Bakar Gandum — Kaya', price: 25000, desc: 'Roti gandum bakar dengan selai kaya' },
  { id: 'roti-bakar-nanas',   cat: 'snacks', name: 'Roti Bakar Gandum — Nanas', price: 25000, desc: 'Roti gandum bakar dengan selai nanas' },
  { id: 'roti-bakar-nutella', cat: 'snacks', name: 'Roti Bakar Gandum — Nutella', price: 28000, desc: 'Roti gandum bakar dengan Nutella' },
  { id: 'roti-bakar-abon',    cat: 'snacks', name: 'Roti Bakar Gandum — Abon', price: 28000, desc: 'Roti gandum bakar dengan abon dan susu kental', photo: '22' },
  { id: 'roti-kukus-jadoel',  cat: 'snacks', name: 'Roti Kukus Gandum — Jadoel', price: 20000, desc: 'Roti gandum kukus klasik, tanpa topping' },
  { id: 'roti-kukus-coklat-susu', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Susu', price: 24000, desc: 'Roti gandum kukus, coklat dan susu kental' },
  { id: 'roti-kukus-keju-susu',   cat: 'snacks', name: 'Roti Kukus Gandum — Keju Susu', price: 24000, desc: 'Roti gandum kukus, keju dan susu kental' },
  { id: 'roti-kukus-coklat-keju', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Keju', price: 25000, desc: 'Roti gandum kukus, coklat dan keju parut' },
  { id: 'roti-kukus-kacang',      cat: 'snacks', name: 'Roti Kukus Gandum — Kacang', price: 28000, desc: 'Roti gandum kukus dengan selai kacang' },
  { id: 'roti-kukus-coklat-kacang', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Kacang', price: 28000, desc: 'Roti gandum kukus, coklat dan kacang' },
  { id: 'roti-kukus-kaya',    cat: 'snacks', name: 'Roti Kukus Gandum — Kaya', price: 25000, desc: 'Roti gandum kukus dengan selai kaya' },
  { id: 'roti-kukus-nanas',   cat: 'snacks', name: 'Roti Kukus Gandum — Nanas', price: 25000, desc: 'Roti gandum kukus dengan selai nanas' },
  { id: 'roti-kukus-nutella', cat: 'snacks', name: 'Roti Kukus Gandum — Nutella', price: 28000, desc: 'Roti gandum kukus dengan Nutella' },
  { id: 'roti-kukus-abon',    cat: 'snacks', name: 'Roti Kukus Gandum — Abon', price: 28000, desc: 'Roti gandum kukus dengan abon dan susu kental' },
  { id: 'french-toast-ori',   cat: 'snacks', name: 'French Toast — Ori', price: 26000, desc: 'Roti panggang telur ala Perancis, polos' },
  { id: 'french-toast-jadoel',cat: 'snacks', name: 'French Toast — Jadoel', price: 28000, desc: 'French toast versi klasik' },
  { id: 'french-toast-coklat-susu', cat: 'snacks', name: 'French Toast — Coklat Susu', price: 32000, desc: 'French toast dengan coklat dan susu kental' },
  { id: 'french-toast-coklat-keju', cat: 'snacks', name: 'French Toast — Coklat Keju', price: 32000, desc: 'French toast dengan coklat dan keju' },
  { id: 'french-toast-coklat-kacang', cat: 'snacks', name: 'French Toast — Coklat Kacang', price: 34000, desc: 'French toast dengan coklat dan kacang' },
  { id: 'french-toast-kaya',  cat: 'snacks', name: 'French Toast — Kaya', price: 34000, desc: 'French toast dengan selai kaya' },
  { id: 'french-toast-nanas', cat: 'snacks', name: 'French Toast — Nanas', price: 32000, desc: 'French toast dengan selai nanas' },
  { id: 'french-toast-nutella', cat: 'snacks', name: 'French Toast — Nutella', price: 33000, desc: 'French toast dengan Nutella' },
  { id: 'french-toast-abon',  cat: 'snacks', name: 'French Toast — Abon', price: 36000, desc: 'French toast dengan abon' },
  { id: 'french-toast-kacang',cat: 'snacks', name: 'French Toast — Kacang', price: 32000, desc: 'French toast dengan selai kacang' },
  { id: 'french-toast-keju-susu', cat: 'snacks', name: 'French Toast — Keju Susu', price: 32000, desc: 'French toast dengan keju dan susu kental' },
  { id: 'cakwe',              cat: 'snacks', name: 'Cakwe (isi 5)', price: 25000, desc: 'Cakwe goreng, gurih dan renyah' },
  { id: 'roti-canay',         cat: 'snacks', name: 'Roti Canay Saos Kari', price: 30000, desc: 'Roti canay berlapis dengan saus kari' },
  { id: 'french-fries',       cat: 'snacks', name: 'French Fries', price: 26000, desc: 'Kentang goreng' },
  { id: 'mix-platter',        cat: 'snacks', name: 'Mix Platter', price: 35000, desc: 'Aneka gorengan dalam satu piring' },
  { id: 'fish-chips',         cat: 'snacks', name: 'Fish & Chips', price: 36000, desc: 'Ikan goreng tepung dengan kentang goreng', photo: '61' },
  { id: 'nachos-original',    cat: 'snacks', name: 'Nachos Original', price: 25000, desc: 'Keripik tortilla dengan saus keju' },
  { id: 'nachos-sambal-matah',cat: 'snacks', name: 'Nachos Sambal Matah', price: 30000, desc: 'Keripik tortilla dengan sambal matah' },
  { id: 'wings-original',     cat: 'snacks', name: 'Chicken Wings Original', price: 30000, desc: 'Sayap ayam goreng bumbu original' },
  { id: 'wings-crispy',       cat: 'snacks', name: 'Chicken Wings Crispy', price: 35000, desc: 'Sayap ayam goreng tepung, renyah' },
  { id: 'wings-korean',       cat: 'snacks', name: 'Chicken Wings Korean Spicy', price: 38000, desc: 'Sayap ayam dengan saus pedas ala Korea' },
  { id: 'bakwan-jagung',      cat: 'snacks', name: 'Bakwan Jagung', price: 26000, desc: 'Bakwan goreng isi jagung' },
  { id: 'bakwan-sayuran',     cat: 'snacks', name: 'Bakwan Sayuran', price: 29000, desc: 'Bakwan goreng isi sayuran' },
  { id: 'bakwan-udang',       cat: 'snacks', name: 'Bakwan Udang', price: 35000, desc: 'Bakwan goreng isi udang' },
  { id: 'indomie-jadoel',     cat: 'snacks', name: 'Indomie Goreng Jadoel', price: 18000, desc: 'Indomie goreng disajikan sederhana' },
  { id: 'indomie-kuah',       cat: 'snacks', name: 'Indomie Goreng Kuah', price: 20000, desc: 'Indomie kuah hangat' },
  { id: 'indomie-tac-tac',    cat: 'snacks', name: 'Indomie Goreng Tac Tac', price: 24000, desc: 'Indomie goreng dengan topping tac tac' },
  { id: 'indomie-nyonya',     cat: 'snacks', name: 'Indomie Goreng Spesial Nyonya', price: 35000, desc: 'Indomie goreng bumbu nyonya, porsi spesial' },
  { id: 'jamur-enoki',        cat: 'snacks', name: 'Jamur Enoki Crispy', price: 28000, desc: 'Jamur enoki goreng tepung, renyah' },
  { id: 'tempe-mendoan',      cat: 'snacks', name: 'Tempe Mendoan', price: 20000, desc: 'Tempe goreng tepung tipis, lembut di dalam' },
  { id: 'sate-taichan',       cat: 'snacks', name: 'Sate Taichan', price: 28000, desc: 'Sate ayam tanpa bumbu kacang, dengan sambal pedas', photo: '23' },
  { id: 'sate-ayam-kacang',   cat: 'snacks', name: 'Sate Ayam Kacang / Madura', price: 35000, desc: 'Sate ayam dengan bumbu kacang', photo: '34', tag: 'Bestseller' },
  { id: 'tekwan',             cat: 'snacks', name: 'Tekwan', price: 26000, desc: 'Sup bola ikan bening, khas Palembang' },
  { id: 'tekwan-indomie',     cat: 'snacks', name: 'Tekwan + Indomie', price: 32000, desc: 'Tekwan disajikan bersama Indomie' },
  { id: 'pempek-crispy',      cat: 'snacks', name: 'Pempek Crispy (isi 3)', price: 20000, desc: 'Pempek goreng renyah, dengan cuko' },
  { id: 'pempek-kecil',       cat: 'snacks', name: 'Pempek Kecil (isi 5)', price: 35000, desc: 'Pempek ukuran kecil, dengan cuko' },
  { id: 'pempek-cerewet',     cat: 'snacks', name: 'Pempek Cerewet (isi 5)', price: 35000, desc: 'Pempek cerewet khas Palembang, dengan cuko' },

  /* ---------------- LAUK ---------------- */
  { id: 'ayam-karage',        cat: 'lauk', name: 'Ayam Goreng Karage', price: 38000, desc: 'Ayam goreng tepung ala Jepang' },
  { id: 'ayam-mentega',       cat: 'lauk', name: 'Ayam Goreng Mentega', price: 38000, desc: 'Ayam goreng dengan saus mentega gurih' },
  { id: 'ayam-bawang-putih',  cat: 'lauk', name: 'Ayam Goreng Bawang Putih', price: 45000, desc: 'Ayam goreng bumbu bawang putih' },
  { id: 'ayam-sambal-matah',  cat: 'lauk', name: 'Ayam Goreng Sambal Matah', price: 38000, desc: 'Ayam goreng dengan sambal matah khas Bali' },
  { id: 'ayam-asam-manis',    cat: 'lauk', name: 'Ayam Saos Asam Manis', price: 38000, desc: 'Ayam goreng dengan saus asam manis', photo: '43' },
  { id: 'ayam-saos-padang',   cat: 'lauk', name: 'Ayam Saos Padang', price: 38000, desc: 'Ayam dengan saus padang, pedas' },
  { id: 'ayam-saos-lemon',    cat: 'lauk', name: 'Ayam Saos Lemon', price: 38000, desc: 'Ayam goreng dengan saus lemon segar' },
  { id: 'ayam-chasiu',        cat: 'lauk', name: 'Ayam Chasiu', price: 38000, desc: 'Ayam bumbu chasiu, manis gurih' },
  { id: 'ayam-korean-spicy',  cat: 'lauk', name: 'Ayam Goreng Korean Spicy', price: 40000, desc: 'Ayam goreng dengan saus pedas ala Korea' },
  { id: 'ayam-telur-asin',    cat: 'lauk', name: 'Ayam Goreng Telur Asin', price: 35000, desc: 'Ayam goreng dengan saus telur asin' },
  { id: 'chicken-katsu',      cat: 'lauk', name: 'Chicken Katsu', price: 35000, desc: 'Ayam goreng tepung panko ala Jepang' },
  { id: 'cumi-telur-asin',    cat: 'lauk', name: 'Cumi Telur Asin', price: 45000, desc: 'Cumi goreng dengan saus telur asin' },
  { id: 'cumi-cabe-garam',    cat: 'lauk', name: 'Cumi Cabe Garam', price: 45000, desc: 'Cumi goreng bumbu cabe garam' },
  { id: 'cumi-crispy',        cat: 'lauk', name: 'Cumi Goreng Crispy', price: 45000, desc: 'Cumi goreng tepung, renyah' },
  { id: 'cumi-asam-manis',    cat: 'lauk', name: 'Cumi Saos Asam Manis', price: 45000, desc: 'Cumi dengan saus asam manis' },
  { id: 'cumi-saos-padang',   cat: 'lauk', name: 'Cumi Saos Padang', price: 45000, desc: 'Cumi dengan saus padang, pedas' },
  { id: 'cumi-saos-lemon',    cat: 'lauk', name: 'Cumi Saos Lemon', price: 45000, desc: 'Cumi dengan saus lemon segar' },
  { id: 'udang-saos-madu',    cat: 'lauk', name: 'Udang Goreng Saos Madu', price: 50000, desc: 'Udang goreng dengan saus madu' },
  { id: 'udang-mentega',      cat: 'lauk', name: 'Udang Goreng Mentega', price: 50000, desc: 'Udang goreng dengan saus mentega' },
  { id: 'udang-mayonaise',    cat: 'lauk', name: 'Udang Goreng Mayonaise', price: 50000, desc: 'Udang goreng dengan saus mayones' },
  { id: 'udang-telur-asin',   cat: 'lauk', name: 'Udang Goreng Telur Asin', price: 50000, desc: 'Udang goreng dengan saus telur asin' },
  { id: 'udang-asam-manis',   cat: 'lauk', name: 'Udang Goreng Asam Manis', price: 50000, desc: 'Udang goreng dengan saus asam manis' },
  { id: 'udang-saos-padang',  cat: 'lauk', name: 'Udang Goreng Saos Padang', price: 50000, desc: 'Udang dengan saus padang, pedas' },
  { id: 'udang-sambal-pete',  cat: 'lauk', name: 'Udang Sambal Pete', price: 65000, desc: 'Udang dengan sambal dan pete' },
  { id: 'dori-sambal-matah',  cat: 'lauk', name: 'Dori Sambal Matah', price: 36000, desc: 'Ikan dori dengan sambal matah' },
  { id: 'dori-saos-lemon',    cat: 'lauk', name: 'Dori Saos Lemon', price: 36000, desc: 'Ikan dori dengan saus lemon segar' },
  { id: 'dori-saos-padang',   cat: 'lauk', name: 'Dori Saos Padang', price: 36000, desc: 'Ikan dori dengan saus padang, pedas' },
  { id: 'dori-asam-manis',    cat: 'lauk', name: 'Dori Saos Asam Manis', price: 36000, desc: 'Ikan dori dengan saus asam manis' },
  { id: 'dori-salted-egg',    cat: 'lauk', name: 'Dori Salted Egg', price: 36000, desc: 'Ikan dori dengan saus telur asin' },
  { id: 'cah-sapi-lada-hitam',cat: 'lauk', name: 'Cah Sapi Lada Hitam', price: 45000, desc: 'Tumis daging sapi saus lada hitam', photo: '56' },
  { id: 'sapi-saos-bbq',      cat: 'lauk', name: 'Sapi Saos BBQ', price: 45000, desc: 'Daging sapi dengan saus barbeque' },
  { id: 'daging-malbi',       cat: 'lauk', name: 'Daging Malbi', price: 25000, desc: 'Daging sapi malbi, manis gurih khas Palembang' },
  { id: 'gurame-thailand',    cat: 'lauk', name: 'Gurame Saos Thailand', price: 27000, desc: 'Per ons' },
  { id: 'gurame-asam-manis',  cat: 'lauk', name: 'Gurame Asam Manis', price: 27000, desc: 'Per ons' },
  { id: 'gurame-tahu-taushi', cat: 'lauk', name: 'Gurame Tahu Taushi', price: 28000, desc: 'Per ons' },
  { id: 'gurame-bakar',       cat: 'lauk', name: 'Gurame Bakar', price: 27000, desc: 'Per ons' },
  { id: 'gurame-saos-padang', cat: 'lauk', name: 'Gurame Saos Padang', price: 27000, desc: 'Per ons' },
  { id: 'nasi-putih',         cat: 'lauk', name: 'Nasi Putih', price: 8000, desc: 'Sepiring nasi putih' },
  { id: 'telur-ayam-satuan',  cat: 'lauk', name: 'Telur Ayam (satuan)', price: 4000, desc: 'Telur ayam, per butir' },
  { id: 'telur-kampung-satuan', cat: 'lauk', name: 'Telur Ayam Kampung (satuan)', price: 6000, desc: 'Telur ayam kampung, per butir' },

  /* ---------------- SAYUR ---------------- */
  { id: 'brokoli-bawang-putih', cat: 'sayur', name: 'Brokoli Cah Bawang Putih', price: 32000, desc: 'Brokoli tumis bawang putih' },
  { id: 'brokoli-saos-kepiting',cat: 'sayur', name: 'Brokoli Saos Kepiting', price: 36000, desc: 'Brokoli dengan saus kepiting' },
  { id: 'brokoli-saos-tiram',   cat: 'sayur', name: 'Brokoli Saos Tiram', price: 35000, desc: 'Brokoli tumis saus tiram' },
  { id: 'brokoli-cah-sapi',     cat: 'sayur', name: 'Brokoli Cah Sapi', price: 45000, desc: 'Brokoli tumis dengan irisan daging sapi' },
  { id: 'cah-kangkung',         cat: 'sayur', name: 'Cah Kangkung', price: 20000, desc: 'Kangkung tumis bawang' },
  { id: 'tauge-bawang-putih',   cat: 'sayur', name: 'Tauge Cah Bawang Putih', price: 20000, desc: 'Tauge tumis bawang putih' },
  { id: 'tauge-ikan-asin',      cat: 'sayur', name: 'Tauge Ikan Asin', price: 28000, desc: 'Tauge tumis dengan ikan asin' },
  { id: 'tauge-cah-sapi',       cat: 'sayur', name: 'Tauge Cah Sapi', price: 38000, desc: 'Tauge tumis dengan daging sapi' },
  { id: 'capcay-ayam',          cat: 'sayur', name: 'Capcay Ayam', price: 35000, desc: 'Aneka sayuran tumis dengan ayam' },
  { id: 'capcay-seafood',       cat: 'sayur', name: 'Capcay Seafood', price: 38000, desc: 'Aneka sayuran tumis dengan seafood' },
  { id: 'fuyunghai',            cat: 'sayur', name: 'Fuyunghai', price: 35000, desc: 'Telur dadar isi sayur, saus asam manis' },
  { id: 'tofu-cabe-garam',      cat: 'sayur', name: 'Tofu Cabe Garam', price: 30000, desc: 'Tahu goreng bumbu cabe garam' },
  { id: 'singapore-tofu',       cat: 'sayur', name: 'Singapore Tofu', price: 35000, desc: 'Tahu goreng dengan saus ala Singapura' },
  { id: 'sapo-tahu-ayam',       cat: 'sayur', name: 'Sapo Tahu Ayam', price: 30000, desc: 'Tahu dan ayam berkuah kental dalam claypot' },
  { id: 'sapo-tahu-seafood',    cat: 'sayur', name: 'Sapo Tahu Seafood', price: 40000, desc: 'Tahu dan seafood berkuah kental dalam claypot' },

  /* ---------------- SOUP ---------------- */
  { id: 'sop-ayam-nyonya',    cat: 'soup', name: 'Sop Ayam Nyonya', price: 36000, desc: 'Sop ayam bening bumbu nyonya', photo: '31' },
  { id: 'sop-daging-sapi',    cat: 'soup', name: 'Sop Daging Sapi', price: 45000, desc: 'Sop bening dengan daging sapi' },
  { id: 'sop-tulang-sapi',    cat: 'soup', name: 'Sop Tulang Sapi', price: 45000, desc: 'Sop bening dengan tulang sapi' },
  { id: 'sop-ayam-kampung',   cat: 'soup', name: 'Sop Ayam Kampung', price: 55000, desc: 'Sop bening dengan ayam kampung' },
  { id: 'sop-buntut-kuah',    cat: 'soup', name: 'Sop Buntut Kuah', price: 80000, desc: 'Buntut sapi berkuah bening' },
  { id: 'sop-buntut-goreng',  cat: 'soup', name: 'Sop Buntut Goreng Cabe Ijo', price: 80000, desc: 'Buntut sapi goreng dengan sambal cabe ijo', photo: '14' },
  { id: 'soto-ayam-nyonya',   cat: 'soup', name: 'Soto Ayam Nyonya', price: 36000, photo: '42', desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-kari-nyonya',   cat: 'soup', name: 'Soto Kari Nyonya', price: 38000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-daging-sapi',   cat: 'soup', name: 'Soto Daging Sapi', price: 45000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-ayam-kampung',  cat: 'soup', name: 'Soto Ayam Kampung', price: 55000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'pindang-tulang-sapi',cat: 'soup', name: 'Pindang Tulang Sapi', price: 45000, desc: 'Tulang sapi dalam kuah asam pedas khas Palembang', photo: '58' },
  { id: 'pindang-ayam-kampung', cat: 'soup', name: 'Pindang Ayam Kampung', price: 55000, desc: 'Ayam kampung dalam kuah asam pedas' },
  { id: 'iga-bakar',          cat: 'soup', name: 'Iga Bakar', price: 55000, desc: 'Iga sapi bakar berbumbu' },
  { id: 'mun-tahu-ayam',      cat: 'soup', name: 'Mun Tahu Ayam', price: 30000, desc: 'Tahu lembut dengan ayam, kuah kental' },
  { id: 'mapo-tahu-ayam',     cat: 'soup', name: 'Mapo Tahu Ayam', price: 35000, desc: 'Tahu dengan ayam cincang, saus pedas ala Sichuan' },

  /* ---------------- NASI ---------------- */
  { id: 'nasi-ayam-gepuk',        cat: 'nasi', name: 'Nasi Ayam Gepuk', price: 30000, desc: 'Nasi dengan ayam gepuk dan sambal', photo: '51' },
  { id: 'nasi-ayam-gepuk-kampung',cat: 'nasi', name: 'Nasi Ayam Gepuk Kampung', price: 48000, desc: 'Nasi dengan ayam kampung gepuk dan sambal' },
  { id: 'nasi-ayam-karage',       cat: 'nasi', name: 'Nasi Ayam Karage', price: 38000, desc: 'Nasi dengan ayam karage' },
  { id: 'nasi-ayam-teriyaki',     cat: 'nasi', name: 'Nasi Ayam Teriyaki', price: 38000, desc: 'Nasi dengan ayam saus teriyaki' },
  { id: 'nasi-ayam-mentega',      cat: 'nasi', name: 'Nasi Ayam Mentega', price: 38000, desc: 'Nasi dengan ayam saus mentega' },
  { id: 'nasi-ayam-saos-lemon',   cat: 'nasi', name: 'Nasi Ayam Saos Lemon', price: 38000, desc: 'Nasi dengan ayam saus lemon' },
  { id: 'nasi-ayam-sambal-matah', cat: 'nasi', name: 'Nasi Ayam Sambal Matah', price: 38000, desc: 'Nasi dengan ayam sambal matah' },
  { id: 'nasi-ayam-saos-padang',  cat: 'nasi', name: 'Nasi Ayam Saos Padang', price: 38000, desc: 'Nasi dengan ayam saus padang' },
  { id: 'nasi-ayam-asam-manis',   cat: 'nasi', name: 'Nasi Ayam Asam Manis', price: 38000, desc: 'Nasi dengan ayam asam manis' },
  { id: 'nasi-ayam-salted-egg',   cat: 'nasi', name: 'Nasi Ayam Salted Egg', price: 38000, desc: 'Nasi dengan ayam saus telur asin' },
  { id: 'nasi-ayam-korean-spicy', cat: 'nasi', name: 'Nasi Ayam Korean Spicy', price: 38000, desc: 'Nasi dengan ayam saus pedas Korea' },
  { id: 'nasi-chicken-katsu',     cat: 'nasi', name: 'Nasi Chicken Katsu', price: 38000, desc: 'Nasi dengan chicken katsu' },
  { id: 'nasi-chicken-hainan',    cat: 'nasi', name: 'Nasi Chicken Hainan', price: 38000, desc: 'Nasi hainan dengan ayam rebus' },
  { id: 'nasi-katsu-curry',       cat: 'nasi', name: 'Nasi Chicken Katsu Curry', price: 40000, desc: 'Nasi dengan chicken katsu dan saus kari' },
  { id: 'nasi-dori-asam-manis',   cat: 'nasi', name: 'Nasi Dori Asam Manis', price: 38000, desc: 'Nasi dengan dori saus asam manis', photo: '33' },
  { id: 'nasi-dori-saos-padang',  cat: 'nasi', name: 'Nasi Dori Saos Padang', price: 38000, desc: 'Nasi dengan dori saus padang' },
  { id: 'nasi-dori-sambal-matah', cat: 'nasi', name: 'Nasi Dori Sambal Matah', price: 38000, desc: 'Nasi dengan dori dan sambal matah', photo: '01', tag: 'Favorit' },
  { id: 'nasi-dori-saos-lemon',   cat: 'nasi', name: 'Nasi Dori Saos Lemon', price: 38000, desc: 'Nasi dengan dori saus lemon' },
  { id: 'nasi-dori-salted-egg',   cat: 'nasi', name: 'Nasi Dori Salted Egg', price: 38000, desc: 'Nasi dengan dori saus telur asin' },
  { id: 'nasi-bakar-teri',        cat: 'nasi', name: 'Nasi Bakar Teri', price: 38000, desc: 'Nasi bakar daun pisang isi teri', photo: '25' },
  { id: 'nasi-bakar-cumi',        cat: 'nasi', name: 'Nasi Bakar Cumi', price: 40000, desc: 'Nasi bakar daun pisang isi cumi' },
  { id: 'nasi-siram-teriyaki',    cat: 'nasi', name: 'Nasi Siram Teriyaki', price: 38000, desc: 'Nasi disiram saus teriyaki' },
  { id: 'nasi-sapi-lada-hitam',   cat: 'nasi', name: 'Nasi Sapi Lada Hitam', price: 45000, desc: 'Nasi dengan sapi lada hitam' },
  { id: 'nasi-sapi-barbeque',     cat: 'nasi', name: 'Nasi Sapi Barbeque', price: 45000, desc: 'Nasi dengan sapi saus barbeque' },
  { id: 'nasi-siram-sapi',        cat: 'nasi', name: 'Nasi Siram Sapi', price: 45000, desc: 'Nasi disiram tumis daging sapi' },

  /* ---------------- MIE ---------------- */
  { id: 'mie-tumis-jawa',     cat: 'mie', name: 'Mie Tumis Jawa', price: 32000, desc: 'Mie tumis bumbu Jawa' },
  { id: 'mie-goreng-jadoel',  cat: 'mie', name: 'Mie Goreng Jadoel', price: 32000, desc: 'Mie goreng klasik ala rumahan', photo: '47', tag: 'Favorit' },
  { id: 'mie-goreng-seafood', cat: 'mie', name: 'Mie Goreng Seafood', price: 38000, desc: 'Mie goreng dengan seafood' },
  { id: 'mie-goreng-siram-sapi', cat: 'mie', name: 'Mie Goreng Siram Sapi', price: 48000, desc: 'Mie goreng disiram tumis daging sapi' },
  { id: 'bihun-goreng-jadoel',cat: 'mie', name: 'Bihun Goreng Jadoel', price: 32000, desc: 'Bihun goreng klasik' },
  { id: 'bihun-goreng-seafood', cat: 'mie', name: 'Bihun Goreng Seafood', price: 38000, desc: 'Bihun goreng dengan seafood' },
  { id: 'bihun-ayam-curry',   cat: 'mie', name: 'Bihun Ayam Curry', price: 40000, desc: 'Bihun dengan kuah kari ayam', photo: '10' },
  { id: 'bihun-goreng-nyonya',cat: 'mie', name: 'Bihun Goreng Nyonya', price: 45000, desc: 'Bihun goreng bumbu nyonya' },
  { id: 'mie-ayam-curry',     cat: 'mie', name: 'Mie Ayam Curry', price: 40000, desc: 'Mie dengan kuah kari ayam' },
  { id: 'mie-goreng-nyonya',  cat: 'mie', name: 'Mie Goreng Nyonya', price: 45000, desc: 'Mie goreng bumbu nyonya' },
  { id: 'kwetiaw-ayam-cincang', cat: 'mie', name: 'Kwetiaw Ayam Cincang', price: 28000, desc: 'Kwetiau dengan ayam cincang' },
  { id: 'kwetiaw-ayam-suwir', cat: 'mie', name: 'Kwetiaw Ayam Kampung Suwir', price: 30000, desc: 'Kwetiau dengan suwiran ayam kampung' },
  { id: 'kwetiaw-goreng-ayam',cat: 'mie', name: 'Kwetiaw Goreng Ayam', price: 35000, desc: 'Kwetiau goreng dengan ayam' },
  { id: 'kwetiaw-singapore',  cat: 'mie', name: 'Kwetiaw Singapore', price: 35000, desc: 'Kwetiau goreng bumbu kari ala Singapura' },
  { id: 'kwetiaw-goreng-seafood', cat: 'mie', name: 'Kwetiaw Goreng Seafood', price: 40000, desc: 'Kwetiau goreng dengan seafood' },
  { id: 'kwetiaw-goreng-sapi',cat: 'mie', name: 'Kwetiaw Goreng Sapi', price: 48000, desc: 'Kwetiau goreng dengan daging sapi' },

  /* ---------------- NASI GORENG ---------------- */
  { id: 'nasgor-merah-jadoel',cat: 'nasgor', name: 'Nasi Goreng Merah Jadoel', price: 30000, desc: 'Nasi goreng merah klasik' },
  { id: 'nasgor-jadoel',      cat: 'nasgor', name: 'Nasi Goreng Jadoel', price: 30000, desc: 'Nasi goreng klasik ala rumahan', tag: 'Bestseller' },
  { id: 'nasgor-cabe-ijo',    cat: 'nasgor', name: 'Nasi Goreng Cabe Ijo', price: 35000, desc: 'Nasi goreng dengan sambal cabe ijo' },
  { id: 'nasgor-ikan-asin',   cat: 'nasgor', name: 'Nasi Goreng Ikan Asin', price: 38000, desc: 'Nasi goreng dengan ikan asin' },
  { id: 'nasgor-pete',        cat: 'nasgor', name: 'Nasi Goreng Pete', price: 38000, desc: 'Nasi goreng dengan pete' },
  { id: 'nasgor-seafood',     cat: 'nasgor', name: 'Nasi Goreng Seafood', price: 38000, desc: 'Nasi goreng dengan seafood' },
  { id: 'nasgor-nyonya-kampung', cat: 'nasgor', name: 'Nasi Goreng Nyonya Kampung', price: 55000, desc: 'Nasi goreng nyonya dengan ayam kampung' },
  { id: 'nasgor-hongkong',    cat: 'nasgor', name: 'Nasi Goreng Hongkong', price: 38000, desc: 'Nasi goreng ala Hongkong' },
  { id: 'nasgor-merah-spesial', cat: 'nasgor', name: 'Nasi Goreng Merah Spesial', price: 48000, desc: 'Nasi goreng merah porsi spesial' },
  { id: 'nasgor-nyonya',      cat: 'nasgor', name: 'Nasi Goreng Nyonya', price: 45000, desc: 'Nasi goreng bumbu nyonya' },
  { id: 'nasgor-yang-zhou',   cat: 'nasgor', name: 'Nasi Goreng Yang Zhou', price: 38000, desc: 'Nasi goreng Yang Zhou dengan aneka isian' },
  { id: 'nasgor-ikan-teri',   cat: 'nasgor', name: 'Nasi Goreng Ikan Teri', price: 35000, desc: 'Nasi goreng dengan ikan teri' },

  /* ---------------- KOPI ---------------- */
  { id: 'kopi-jadoel',        cat: 'coffee', name: 'Kopi Jadoel', price: 10000, photo: '11', tag: 'Signature', desc: 'Kopi hitam ala Palembang' },
  { id: 'kopi-susu',          cat: 'coffee', name: 'Kopi Susu', price: 14000, desc: 'Kopi hitam dengan susu', photo: '54' },
  { id: 'kopi-gula-aren',     cat: 'coffee', name: 'Kopi Gula Aren', price: 16000, desc: 'Kopi susu dengan gula aren' },
  { id: 'kopi-cincau-susu',   cat: 'coffee', name: 'Kopi Cincau Susu', price: 28000, desc: 'Kopi susu dengan cincau hitam' },
  { id: 'kopi-janji-hati',    cat: 'coffee', name: 'Kopi Janji Hati', price: 26000, desc: 'Racikan kopi susu spesial Coffee J', photo: '08', tag: 'Bestseller' },
  { id: 'vietnam-drip',       cat: 'coffee', name: 'Vietnam Drip', price: 25000, desc: 'Kopi tetes ala Vietnam, pekat', photo: '28' },

  /* ---------------- MODERN COFFEE ---------------- */
  { id: 'espresso',           cat: 'modern', name: 'Espresso', price: 18000, desc: 'Sari kopi pekat, satu shot' },
  { id: 'americano',          cat: 'modern', name: 'Americano', price: 20000, desc: 'Espresso dengan tambahan air' },
  { id: 'cappucino',          cat: 'modern', name: 'Cappucino', price: 25000, desc: 'Espresso dengan susu dan busa tebal' },
  { id: 'coffee-latte',       cat: 'modern', name: 'Coffee Latte', price: 26000, desc: 'Espresso dengan susu, lembut' },
  { id: 'caramel-latte',      cat: 'modern', name: 'Caramel Latte', price: 30000, desc: 'Latte dengan sirup karamel' },
  { id: 'hazelnut-latte',     cat: 'modern', name: 'Hazelnut Latte', price: 30000, desc: 'Latte dengan sirup hazelnut' },
  { id: 'vanilla-latte',      cat: 'modern', name: 'Vanilla Latte', price: 28000, desc: 'Latte dengan sirup vanila' },
  { id: 'taro-latte',         cat: 'modern', name: 'Taro Latte', price: 28000, desc: 'Latte taro, manis dan lembut' },
  { id: 'kojo-latte',         cat: 'modern', name: 'Kojo Latte', price: 28000, desc: 'Latte manis dengan aroma pandan' },
  { id: 'blue-salted-latte',  cat: 'modern', name: 'Blue Salted Latte', price: 28000, desc: 'Latte dengan krim asin, warna biru' },
  { id: 'matcha-latte',       cat: 'modern', name: 'Matcha Latte', price: 28000, desc: 'Teh hijau matcha dengan susu' },
  { id: 'choco-latte',        cat: 'modern', name: 'Choco Latte', price: 28000, desc: 'Minuman coklat dengan susu' },
  { id: 'caramel-macchiato',  cat: 'modern', name: 'Caramel Latte Macchiato', price: 35000, desc: 'Espresso, susu dan karamel berlapis' },
  { id: 'blue-salted-macchiato', cat: 'modern', name: 'Blue Salted Latte Macchiato', price: 35000, desc: 'Macchiato dengan krim asin, warna biru' },
  { id: 'klepon-creamy',      cat: 'modern', name: 'Klepon Creamy Cheese', price: 35000, desc: 'Minuman rasa klepon dengan krim keju' },
  { id: 'oreo-creamy',        cat: 'modern', name: 'Oreo Creamy Cheese', price: 36000, desc: 'Minuman Oreo dengan krim keju' },
  { id: 'caramel-creamy',     cat: 'modern', name: 'Caramel Creamy Cheese', price: 36000, desc: 'Minuman karamel dengan krim keju' },
  { id: 'taro-creamy',        cat: 'modern', name: 'Taro Creamy Cheese', price: 32000, desc: 'Minuman taro dengan krim keju' },
  { id: 'matcha-creamy',      cat: 'modern', name: 'Matcha Creamy Cheese', price: 35000, desc: 'Matcha dengan krim keju' },
  { id: 'strawberry-matcha-creamy', cat: 'modern', name: 'Strawberry Matcha Creamy', price: 36000, desc: 'Matcha dan stroberi dengan krim' },

  /* ---------------- TEH ---------------- */
  { id: 'teh-tarik',          cat: 'tea', name: 'Teh Tarik', price: 20000, desc: 'Teh susu tarik, berbusa' },
  { id: 'teh-tarik-chai',     cat: 'tea', name: 'Teh Tarik "Chai Masala"', price: 25000, desc: 'Teh tarik dengan rempah chai masala' },
  { id: 'teh-tarik-cincau',   cat: 'tea', name: 'Teh Tarik Cincau', price: 25000, desc: 'Teh tarik dengan cincau hitam' },
  { id: 'bandrek-jahe',       cat: 'tea', name: 'Bandrek Jahe', price: 20000, desc: 'Minuman jahe hangat berempah' },
  { id: 'bandrek-susu',       cat: 'tea', name: 'Bandrek Susu', price: 23000, desc: 'Bandrek jahe dengan susu' },
  { id: 'bandrek-telor',      cat: 'tea', name: 'Bandrek Telor Kampung', price: 28000, desc: 'Bandrek dengan telur ayam kampung' },
  { id: 'teh-tawar',          cat: 'tea', name: 'Teh Tawar', price: 8000, desc: 'Teh tanpa gula' },
  { id: 'teh-manis',          cat: 'tea', name: 'Teh Manis', price: 10000, desc: 'Teh manis, panas atau dingin' },
  { id: 'dilmah-chinese',     cat: 'tea', name: 'Chinese Tea', price: 30000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-english',     cat: 'tea', name: 'English Breakfast', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-chamomile',   cat: 'tea', name: 'Chamomile', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-peppermint',  cat: 'tea', name: 'Peppermint', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-green',       cat: 'tea', name: 'Green Tea', price: 28000, desc: 'Dilmah — free refill 1x' },

  /* ---------------- ICE CREAM ---------------- */
  { id: 'affogato',           cat: 'icecream', name: 'Affogato Coffee', price: 28000, desc: 'Es krim vanila disiram espresso', photo: '29', focus: '50% 62%' },
  { id: 'avocado-float',      cat: 'icecream', name: 'Avocado Float', price: 36000, desc: 'Alpukat dingin dengan es krim' },
  { id: 'avocado-float-coffee', cat: 'icecream', name: 'Avocado Float Coffee', price: 38000, desc: 'Alpukat dengan kopi dan es krim' },
  { id: 'avocado-vanila',     cat: 'icecream', name: 'Avocado Vanila Ice Cream', price: 38000, desc: 'Alpukat dengan es krim vanila' },
  { id: 'oreo-float',         cat: 'icecream', name: 'Oreo Float', price: 38000, desc: 'Minuman Oreo dengan es krim' },
  { id: 'strawberry-float',   cat: 'icecream', name: 'Strawberry Float', price: 35000, desc: 'Stroberi dingin dengan es krim' },
  { id: 'mango-float',        cat: 'icecream', name: 'Mango Float', price: 35000, desc: 'Mangga dingin dengan es krim' },
  { id: 'chocolate-float',    cat: 'icecream', name: 'Chocolate Float', price: 35000, desc: 'Coklat dingin dengan es krim' },

  /* ---------------- SODA ---------------- */
  { id: 'magic-purple',       cat: 'soda', name: 'Magic Purple', price: 30000, desc: 'Mocktail soda ungu, manis dan segar' },
  { id: 'morning-sunrise',    cat: 'soda', name: 'Morning Sunrise', price: 30000, desc: 'Mocktail soda berlapis warna jingga' },
  { id: 'pink-sunshine',      cat: 'soda', name: 'Pink Sunshine', price: 30000, desc: 'Mocktail soda merah muda, segar' },
  { id: 'mint-grass-mojito',  cat: 'soda', name: 'Mint Grass Mojito', price: 30000, desc: 'Mojito tanpa alkohol dengan daun mint' },
  { id: 'love-poison',        cat: 'soda', name: 'Love Poison', price: 30000, desc: 'Mocktail soda merah, manis segar' },
  { id: 'blue-ocean',         cat: 'soda', name: 'Blue Ocean', price: 30000, desc: 'Mocktail soda biru, segar' },
  { id: 'yellow-cream-lime',  cat: 'soda', name: 'Yellow Cream Lime', price: 30000, desc: 'Soda jeruk nipis dengan krim' },
  { id: 'mango-yuzu-coco',    cat: 'soda', name: 'Mango Yuzu Coco', price: 30000, desc: 'Mangga, yuzu dan kelapa' },
  { id: 'pineapple-conlada',  cat: 'soda', name: 'Pineapple Conlada', price: 30000, desc: 'Nanas dan santan ala pina colada' },
  { id: 'lemon-tea-squash',   cat: 'soda', name: 'Lemon Tea Squash', price: 60000, desc: 'Sharing portion' },
  { id: 'green-tea-squash',   cat: 'soda', name: 'Green Tea Squash', price: 65000, desc: 'Sharing portion' },

  /* ---------------- JUS ---------------- */
  { id: 'jus-nanas',          cat: 'juice', name: 'Jus Nanas', price: 28000, desc: 'Jus nanas segar' },
  { id: 'jus-strawberry',     cat: 'juice', name: 'Jus Strawberry', price: 30000, desc: 'Jus stroberi segar' },
  { id: 'jus-semangka',       cat: 'juice', name: 'Jus Semangka', price: 28000, desc: 'Jus semangka segar' },
  { id: 'jus-sirsak',         cat: 'juice', name: 'Jus Sirsak', price: 30000, desc: 'Jus sirsak segar' },
  { id: 'jus-melon',          cat: 'juice', name: 'Jus Melon', price: 28000, desc: 'Jus melon segar' },
  { id: 'jus-mangga',         cat: 'juice', name: 'Jus Mangga', price: 35000, desc: 'Jus mangga segar' },
  { id: 'jus-avocado',        cat: 'juice', name: 'Jus Avocado', price: 35000, desc: 'Jus alpukat kental' },
  { id: 'jus-mango-berry',    cat: 'juice', name: 'Jus Mango Berry', price: 35000, desc: 'Strawberry + mangga' },
  { id: 'jus-mango-pineapple',cat: 'juice', name: 'Jus Mango Pineapple', price: 35000, desc: 'Nanas + mangga' },
  { id: 'jus-white-mango',    cat: 'juice', name: 'Jus White Mango', price: 35000, desc: 'Sirsak + mangga' },

  /* ---------------- NON-COFFEE ---------------- */
  { id: 'milo',               cat: 'noncoffee', name: 'Milo', price: 28000, desc: 'Minuman coklat malt Milo' },
  { id: 'milo-cincau',        cat: 'noncoffee', name: 'Milo Cincau', price: 35000, desc: 'Milo dengan cincau hitam' },
  { id: 'milo-dinosaurus',    cat: 'noncoffee', name: 'Milo Dinosaurus', price: 36000, desc: 'Milo dingin dengan taburan bubuk Milo' },
  { id: 'ginger-tea',         cat: 'noncoffee', name: 'Ginger Tea', price: 25000, desc: 'Teh jahe hangat' },
  { id: 'honey-lemon-tea',    cat: 'noncoffee', name: 'Honey Lemon Tea', price: 26000, desc: 'Teh lemon dengan madu' },
  { id: 'honey-ginger-lemonade', cat: 'noncoffee', name: 'Honey Ginger Lemonade', price: 30000, desc: 'Lemonade jahe dengan madu' },
  { id: 'lychee-ice-tea',     cat: 'noncoffee', name: 'Lychee Ice Tea', price: 30000, desc: 'Es teh dengan leci' },
  { id: 'lemon-tea',          cat: 'noncoffee', name: 'Lemon Tea', price: 20000, desc: 'Teh dengan perasan lemon' },
  { id: 'honey-lemonade',     cat: 'noncoffee', name: 'Honey Lemonade', price: 26000, desc: 'Lemonade dengan madu' },
  { id: 'jeruk-nipis',        cat: 'noncoffee', name: 'Jeruk Nipis', price: 26000, desc: 'Perasan jeruk nipis segar' },
  { id: 'jeruk-kunci',        cat: 'noncoffee', name: 'Jeruk Kunci', price: 26000, desc: 'Perasan jeruk kunci khas Palembang' },
  { id: 'jeruk-manis',        cat: 'noncoffee', name: 'Jeruk Manis', price: 26000, desc: 'Jus jeruk manis' },
  { id: 'jeruk-murni',        cat: 'noncoffee', name: 'Jeruk Murni', price: 38000, desc: 'Jus jeruk murni tanpa campuran' },
  { id: 'jeruk-nipis-asamboy',cat: 'noncoffee', name: 'Jeruk Nipis Asamboy', price: 28000, desc: 'Jeruk nipis dengan asamboy' },
  { id: 'jeruk-kunci-asamboy',cat: 'noncoffee', name: 'Jeruk Kunci Asamboy', price: 28000, desc: 'Jeruk kunci dengan asamboy' },
  { id: 'jeruk-manis-asamboy',cat: 'noncoffee', name: 'Jeruk Manis Asamboy', price: 28000, desc: 'Jeruk manis dengan asamboy' },

  /* ---------------- MAGNUM ---------------- */
  { id: 'magnum-mango-yogurt',cat: 'magnum', name: 'Magnum Mango Yogurt', price: 53000, desc: 'Es krim Magnum dengan mangga dan yogurt', photo: '44' },
  { id: 'magnum-berry-yogurt',cat: 'magnum', name: 'Magnum Berry Yogurt', price: 53000, desc: 'Es krim Magnum dengan beri dan yogurt' },
  { id: 'magnum-choco-cheese',cat: 'magnum', name: 'Magnum Choco Cheese', price: 53000, desc: 'Es krim Magnum dengan coklat dan krim keju', photo: '59' },
  { id: 'magnum-oreo-cheese', cat: 'magnum', name: 'Magnum Oreo Cheese', price: 53000, desc: 'Es krim Magnum dengan Oreo dan krim keju' },
  { id: 'magnum-matcha-cheese', cat: 'magnum', name: 'Magnum Matcha Cheese', price: 53000, desc: 'Es krim Magnum dengan matcha dan krim keju' },
];

/* Shown as large photo cards at the top of the menu. */
window.CJ_FEATURED = [
  'kopi-jadoel', 'mie-celor', 'roti-bakar-abon',
  'sate-ayam-kacang', 'nasi-dori-sambal-matah', 'soto-ayam-nyonya',
];
