/* ===========================================================
   Coffee J — menu data
   Transcribed from the shop's own menu PDF (Coffee J Menu).
   Prices are rupiah. Printed menu lists them in thousands,
   e.g. "KOPI JADOEL 10" = Rp 10.000.

   `photo` refers to images/dishes/NN.jpg, numbered from the
   raw photo set. Items without a photo render a plain row.
   =========================================================== */

window.CJ_CATEGORIES = [
  { id: 'breakfast', label: 'Breakfast',     note: 'Disajikan dari jam 06.30' },
  { id: 'snacks',    label: 'Snacks' },
  { id: 'lauk',      label: 'Lauk' },
  { id: 'sayur',     label: 'Sayur' },
  { id: 'soup',      label: 'Soup' },
  { id: 'nasi',      label: 'Nasi' },
  { id: 'mie',       label: 'Mie' },
  { id: 'nasgor',    label: 'Nasi Goreng' },
  { id: 'coffee',    label: 'Kopi' },
  { id: 'modern',    label: 'Modern Coffee' },
  { id: 'tea',       label: 'Teh' },
  { id: 'icecream',  label: 'Ice Cream' },
  { id: 'soda',      label: 'Soda' },
  { id: 'juice',     label: 'Jus' },
  { id: 'noncoffee', label: 'Non-Coffee' },
  { id: 'magnum',    label: 'Magnum' },
];

/* id, cat, name, price, optional: desc, photo, tag, focus
   focus sets object-position inside the circular frame, e.g. '50% 68%'
   pulls the crop downward when the dish sits low in the photo. */
window.CJ_MENU = [
  /* ---------------- BREAKFAST ---------------- */
  { id: 'telur-kampung',      cat: 'breakfast', name: 'Telur Ayam Kampung 1/2 Matang', price: 16000 },
  { id: 'bubur-ayam-kampung', cat: 'breakfast', name: 'Bubur Ayam Kampung', price: 30000, photo: '13' },
  { id: 'bubur-ayam-special', cat: 'breakfast', name: 'Bubur Ayam Special', price: 30000, photo: '24', tag: 'Favorit' },
  { id: 'bubur-ikan',         cat: 'breakfast', name: 'Bubur Ikan', price: 30000, photo: '55' },
  { id: 'bubur-ikan-hokian',  cat: 'breakfast', name: 'Bubur Ikan Hokian', price: 38000 },
  { id: 'mie-ayam-suwir',     cat: 'breakfast', name: 'Mie Ayam Kampung Suwir', price: 32000, photo: '46' },
  { id: 'mie-ayam-cincang',   cat: 'breakfast', name: 'Mie Ayam Daging Cincang', price: 30000 },
  { id: 'mie-ayam-chasiu',    cat: 'breakfast', name: 'Mie Ayam Chasiu', price: 30000 },
  { id: 'bihun-ayam-chasiu',  cat: 'breakfast', name: 'Bihun Ayam Chasiu', price: 28000 },
  { id: 'bihun-ayam-cincang', cat: 'breakfast', name: 'Bihun Ayam Cincang', price: 28000 },
  { id: 'bihun-ayam-suwir',   cat: 'breakfast', name: 'Bihun Ayam Kampung Suwir', price: 30000 },
  { id: 'misua-ayam-suwir',   cat: 'breakfast', name: 'Misua Ayam Kampung Suwir', price: 35000, photo: '03' },
  { id: 'misua-ayam-cincang', cat: 'breakfast', name: 'Misua Ayam Cincang', price: 33000 },
  { id: 'kwetiau-goreng-sapi-bf', cat: 'breakfast', name: 'Kwetiau Goreng Sapi', price: 48000 },
  { id: 'lontong-sayur',      cat: 'breakfast', name: 'Lontong Sayur', price: 20000 },
  { id: 'lontong-komplit',    cat: 'breakfast', name: 'Lontong Komplit', price: 26000 },
  { id: 'lontong-special',    cat: 'breakfast', name: 'Lontong Special', price: 42000 },
  { id: 'mie-celor',          cat: 'breakfast', name: 'Mie Celor', price: 28000, photo: '07', focus: '50% 68%', tag: 'Khas Palembang' },
  { id: 'laksan',             cat: 'breakfast', name: 'Laksan', price: 8000 },
  { id: 'lakso',              cat: 'breakfast', name: 'Lakso', price: 12000 },
  { id: 'burgo',              cat: 'breakfast', name: 'Burgo', price: 12000 },
  { id: 'celimpungan',        cat: 'breakfast', name: 'Celimpungan (isi 3)', price: 16000 },
  { id: 'topping-bakso-sapi', cat: 'breakfast', name: 'Topping — Bakso Sapi', price: 10000 },
  { id: 'topping-bakso-ayam', cat: 'breakfast', name: 'Topping — Bakso Ayam', price: 10000 },

  /* ---------------- SNACKS ---------------- */
  { id: 'pisang-jadoel',      cat: 'snacks', name: 'Pisang Goreng Jadoel', price: 20000 },
  { id: 'pisang-keju-susu',   cat: 'snacks', name: 'Pisang Goreng Keju Susu', price: 24000 },
  { id: 'pisang-coklat-susu', cat: 'snacks', name: 'Pisang Goreng Coklat Susu', price: 24000 },
  { id: 'pisang-coklat-keju', cat: 'snacks', name: 'Pisang Goreng Coklat Keju', price: 26000 },
  { id: 'ubi-jepang',         cat: 'snacks', name: 'Ubi ala Jepang', price: 26000 },
  { id: 'siomay-ayam',        cat: 'snacks', name: 'Siomay Ayam', price: 25000, photo: '05' },
  { id: 'siomay-rumput-laut', cat: 'snacks', name: 'Siomay Rumput Laut', price: 25000 },
  { id: 'ekado-kepiting',     cat: 'snacks', name: 'Ekado Kepiting', price: 25000 },
  { id: 'lumpiah-seafood',    cat: 'snacks', name: 'Lumpiah Seafood', price: 25000 },
  { id: 'mantao-original',    cat: 'snacks', name: 'Mantao Original (isi 3)', price: 28000, photo: '60', tag: 'Favorit' },
  { id: 'bakpao-ayam-merah',  cat: 'snacks', name: 'Bakpao Ayam Merah (isi 3)', price: 28000, photo: '50' },
  { id: 'roti-bakar-jadoel',  cat: 'snacks', name: 'Roti Bakar Gandum — Jadoel', price: 20000 },
  { id: 'roti-bakar-coklat-susu', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Susu', price: 24000 },
  { id: 'roti-bakar-keju-susu',   cat: 'snacks', name: 'Roti Bakar Gandum — Keju Susu', price: 24000 },
  { id: 'roti-bakar-coklat-keju', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Keju', price: 25000, tag: 'Bestseller' },
  { id: 'roti-bakar-kacang',      cat: 'snacks', name: 'Roti Bakar Gandum — Kacang', price: 28000 },
  { id: 'roti-bakar-coklat-kacang', cat: 'snacks', name: 'Roti Bakar Gandum — Coklat Kacang', price: 28000 },
  { id: 'roti-bakar-kaya',    cat: 'snacks', name: 'Roti Bakar Gandum — Kaya', price: 25000 },
  { id: 'roti-bakar-nanas',   cat: 'snacks', name: 'Roti Bakar Gandum — Nanas', price: 25000 },
  { id: 'roti-bakar-nutella', cat: 'snacks', name: 'Roti Bakar Gandum — Nutella', price: 28000 },
  { id: 'roti-bakar-abon',    cat: 'snacks', name: 'Roti Bakar Gandum — Abon', price: 28000, photo: '22' },
  { id: 'roti-kukus-jadoel',  cat: 'snacks', name: 'Roti Kukus Gandum — Jadoel', price: 20000 },
  { id: 'roti-kukus-coklat-susu', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Susu', price: 24000 },
  { id: 'roti-kukus-keju-susu',   cat: 'snacks', name: 'Roti Kukus Gandum — Keju Susu', price: 24000 },
  { id: 'roti-kukus-coklat-keju', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Keju', price: 25000 },
  { id: 'roti-kukus-kacang',      cat: 'snacks', name: 'Roti Kukus Gandum — Kacang', price: 28000 },
  { id: 'roti-kukus-coklat-kacang', cat: 'snacks', name: 'Roti Kukus Gandum — Coklat Kacang', price: 28000 },
  { id: 'roti-kukus-kaya',    cat: 'snacks', name: 'Roti Kukus Gandum — Kaya', price: 25000 },
  { id: 'roti-kukus-nanas',   cat: 'snacks', name: 'Roti Kukus Gandum — Nanas', price: 25000 },
  { id: 'roti-kukus-nutella', cat: 'snacks', name: 'Roti Kukus Gandum — Nutella', price: 28000 },
  { id: 'roti-kukus-abon',    cat: 'snacks', name: 'Roti Kukus Gandum — Abon', price: 28000 },
  { id: 'french-toast-ori',   cat: 'snacks', name: 'French Toast — Ori', price: 26000 },
  { id: 'french-toast-jadoel',cat: 'snacks', name: 'French Toast — Jadoel', price: 28000 },
  { id: 'french-toast-coklat-susu', cat: 'snacks', name: 'French Toast — Coklat Susu', price: 32000 },
  { id: 'french-toast-coklat-keju', cat: 'snacks', name: 'French Toast — Coklat Keju', price: 32000 },
  { id: 'french-toast-coklat-kacang', cat: 'snacks', name: 'French Toast — Coklat Kacang', price: 34000 },
  { id: 'french-toast-kaya',  cat: 'snacks', name: 'French Toast — Kaya', price: 34000 },
  { id: 'french-toast-nanas', cat: 'snacks', name: 'French Toast — Nanas', price: 32000 },
  { id: 'french-toast-nutella', cat: 'snacks', name: 'French Toast — Nutella', price: 33000 },
  { id: 'french-toast-abon',  cat: 'snacks', name: 'French Toast — Abon', price: 36000 },
  { id: 'french-toast-kacang',cat: 'snacks', name: 'French Toast — Kacang', price: 32000 },
  { id: 'french-toast-keju-susu', cat: 'snacks', name: 'French Toast — Keju Susu', price: 32000 },
  { id: 'cakwe',              cat: 'snacks', name: 'Cakwe (isi 5)', price: 25000 },
  { id: 'roti-canay',         cat: 'snacks', name: 'Roti Canay Saos Kari', price: 30000 },
  { id: 'french-fries',       cat: 'snacks', name: 'French Fries', price: 26000 },
  { id: 'mix-platter',        cat: 'snacks', name: 'Mix Platter', price: 35000 },
  { id: 'fish-chips',         cat: 'snacks', name: 'Fish & Chips', price: 36000, photo: '61' },
  { id: 'nachos-original',    cat: 'snacks', name: 'Nachos Original', price: 25000 },
  { id: 'nachos-sambal-matah',cat: 'snacks', name: 'Nachos Sambal Matah', price: 30000 },
  { id: 'wings-original',     cat: 'snacks', name: 'Chicken Wings Original', price: 30000 },
  { id: 'wings-crispy',       cat: 'snacks', name: 'Chicken Wings Crispy', price: 35000 },
  { id: 'wings-korean',       cat: 'snacks', name: 'Chicken Wings Korean Spicy', price: 38000 },
  { id: 'bakwan-jagung',      cat: 'snacks', name: 'Bakwan Jagung', price: 26000 },
  { id: 'bakwan-sayuran',     cat: 'snacks', name: 'Bakwan Sayuran', price: 29000 },
  { id: 'bakwan-udang',       cat: 'snacks', name: 'Bakwan Udang', price: 35000 },
  { id: 'indomie-jadoel',     cat: 'snacks', name: 'Indomie Goreng Jadoel', price: 18000 },
  { id: 'indomie-kuah',       cat: 'snacks', name: 'Indomie Goreng Kuah', price: 20000 },
  { id: 'indomie-tac-tac',    cat: 'snacks', name: 'Indomie Goreng Tac Tac', price: 24000 },
  { id: 'indomie-nyonya',     cat: 'snacks', name: 'Indomie Goreng Spesial Nyonya', price: 35000 },
  { id: 'jamur-enoki',        cat: 'snacks', name: 'Jamur Enoki Crispy', price: 28000 },
  { id: 'tempe-mendoan',      cat: 'snacks', name: 'Tempe Mendoan', price: 20000 },
  { id: 'sate-taichan',       cat: 'snacks', name: 'Sate Taichan', price: 28000, photo: '23' },
  { id: 'sate-ayam-kacang',   cat: 'snacks', name: 'Sate Ayam Kacang / Madura', price: 35000, photo: '34', tag: 'Bestseller' },
  { id: 'tekwan',             cat: 'snacks', name: 'Tekwan', price: 26000 },
  { id: 'tekwan-indomie',     cat: 'snacks', name: 'Tekwan + Indomie', price: 32000 },
  { id: 'pempek-crispy',      cat: 'snacks', name: 'Pempek Crispy (isi 3)', price: 20000 },
  { id: 'pempek-kecil',       cat: 'snacks', name: 'Pempek Kecil (isi 5)', price: 35000 },
  { id: 'pempek-cerewet',     cat: 'snacks', name: 'Pempek Cerewet (isi 5)', price: 35000 },

  /* ---------------- LAUK ---------------- */
  { id: 'ayam-karage',        cat: 'lauk', name: 'Ayam Goreng Karage', price: 38000 },
  { id: 'ayam-mentega',       cat: 'lauk', name: 'Ayam Goreng Mentega', price: 38000 },
  { id: 'ayam-bawang-putih',  cat: 'lauk', name: 'Ayam Goreng Bawang Putih', price: 45000 },
  { id: 'ayam-sambal-matah',  cat: 'lauk', name: 'Ayam Goreng Sambal Matah', price: 38000 },
  { id: 'ayam-asam-manis',    cat: 'lauk', name: 'Ayam Saos Asam Manis', price: 38000, photo: '43' },
  { id: 'ayam-saos-padang',   cat: 'lauk', name: 'Ayam Saos Padang', price: 38000 },
  { id: 'ayam-saos-lemon',    cat: 'lauk', name: 'Ayam Saos Lemon', price: 38000 },
  { id: 'ayam-chasiu',        cat: 'lauk', name: 'Ayam Chasiu', price: 38000 },
  { id: 'ayam-korean-spicy',  cat: 'lauk', name: 'Ayam Goreng Korean Spicy', price: 40000 },
  { id: 'ayam-telur-asin',    cat: 'lauk', name: 'Ayam Goreng Telur Asin', price: 35000 },
  { id: 'chicken-katsu',      cat: 'lauk', name: 'Chicken Katsu', price: 35000 },
  { id: 'cumi-telur-asin',    cat: 'lauk', name: 'Cumi Telur Asin', price: 45000 },
  { id: 'cumi-cabe-garam',    cat: 'lauk', name: 'Cumi Cabe Garam', price: 45000 },
  { id: 'cumi-crispy',        cat: 'lauk', name: 'Cumi Goreng Crispy', price: 45000 },
  { id: 'cumi-asam-manis',    cat: 'lauk', name: 'Cumi Saos Asam Manis', price: 45000 },
  { id: 'cumi-saos-padang',   cat: 'lauk', name: 'Cumi Saos Padang', price: 45000 },
  { id: 'cumi-saos-lemon',    cat: 'lauk', name: 'Cumi Saos Lemon', price: 45000 },
  { id: 'udang-saos-madu',    cat: 'lauk', name: 'Udang Goreng Saos Madu', price: 50000 },
  { id: 'udang-mentega',      cat: 'lauk', name: 'Udang Goreng Mentega', price: 50000 },
  { id: 'udang-mayonaise',    cat: 'lauk', name: 'Udang Goreng Mayonaise', price: 50000 },
  { id: 'udang-telur-asin',   cat: 'lauk', name: 'Udang Goreng Telur Asin', price: 50000 },
  { id: 'udang-asam-manis',   cat: 'lauk', name: 'Udang Goreng Asam Manis', price: 50000 },
  { id: 'udang-saos-padang',  cat: 'lauk', name: 'Udang Goreng Saos Padang', price: 50000 },
  { id: 'udang-sambal-pete',  cat: 'lauk', name: 'Udang Sambal Pete', price: 65000 },
  { id: 'dori-sambal-matah',  cat: 'lauk', name: 'Dori Sambal Matah', price: 36000 },
  { id: 'dori-saos-lemon',    cat: 'lauk', name: 'Dori Saos Lemon', price: 36000 },
  { id: 'dori-saos-padang',   cat: 'lauk', name: 'Dori Saos Padang', price: 36000 },
  { id: 'dori-asam-manis',    cat: 'lauk', name: 'Dori Saos Asam Manis', price: 36000 },
  { id: 'dori-salted-egg',    cat: 'lauk', name: 'Dori Salted Egg', price: 36000 },
  { id: 'cah-sapi-lada-hitam',cat: 'lauk', name: 'Cah Sapi Lada Hitam', price: 45000, photo: '56' },
  { id: 'sapi-saos-bbq',      cat: 'lauk', name: 'Sapi Saos BBQ', price: 45000 },
  { id: 'daging-malbi',       cat: 'lauk', name: 'Daging Malbi', price: 25000 },
  { id: 'gurame-thailand',    cat: 'lauk', name: 'Gurame Saos Thailand', price: 27000, desc: 'Per ons' },
  { id: 'gurame-asam-manis',  cat: 'lauk', name: 'Gurame Asam Manis', price: 27000, desc: 'Per ons' },
  { id: 'gurame-tahu-taushi', cat: 'lauk', name: 'Gurame Tahu Taushi', price: 28000, desc: 'Per ons' },
  { id: 'gurame-bakar',       cat: 'lauk', name: 'Gurame Bakar', price: 27000, desc: 'Per ons' },
  { id: 'gurame-saos-padang', cat: 'lauk', name: 'Gurame Saos Padang', price: 27000, desc: 'Per ons' },
  { id: 'nasi-putih',         cat: 'lauk', name: 'Nasi Putih', price: 8000 },
  { id: 'telur-ayam-satuan',  cat: 'lauk', name: 'Telur Ayam (satuan)', price: 4000 },
  { id: 'telur-kampung-satuan', cat: 'lauk', name: 'Telur Ayam Kampung (satuan)', price: 6000 },

  /* ---------------- SAYUR ---------------- */
  { id: 'brokoli-bawang-putih', cat: 'sayur', name: 'Brokoli Cah Bawang Putih', price: 32000 },
  { id: 'brokoli-saos-kepiting',cat: 'sayur', name: 'Brokoli Saos Kepiting', price: 36000 },
  { id: 'brokoli-saos-tiram',   cat: 'sayur', name: 'Brokoli Saos Tiram', price: 35000 },
  { id: 'brokoli-cah-sapi',     cat: 'sayur', name: 'Brokoli Cah Sapi', price: 45000 },
  { id: 'cah-kangkung',         cat: 'sayur', name: 'Cah Kangkung', price: 20000 },
  { id: 'tauge-bawang-putih',   cat: 'sayur', name: 'Tauge Cah Bawang Putih', price: 20000 },
  { id: 'tauge-ikan-asin',      cat: 'sayur', name: 'Tauge Ikan Asin', price: 28000 },
  { id: 'tauge-cah-sapi',       cat: 'sayur', name: 'Tauge Cah Sapi', price: 38000 },
  { id: 'capcay-ayam',          cat: 'sayur', name: 'Capcay Ayam', price: 35000 },
  { id: 'capcay-seafood',       cat: 'sayur', name: 'Capcay Seafood', price: 38000 },
  { id: 'fuyunghai',            cat: 'sayur', name: 'Fuyunghai', price: 35000 },
  { id: 'tofu-cabe-garam',      cat: 'sayur', name: 'Tofu Cabe Garam', price: 30000 },
  { id: 'singapore-tofu',       cat: 'sayur', name: 'Singapore Tofu', price: 35000 },
  { id: 'sapo-tahu-ayam',       cat: 'sayur', name: 'Sapo Tahu Ayam', price: 30000 },
  { id: 'sapo-tahu-seafood',    cat: 'sayur', name: 'Sapo Tahu Seafood', price: 40000 },

  /* ---------------- SOUP ---------------- */
  { id: 'sop-ayam-nyonya',    cat: 'soup', name: 'Sop Ayam Nyonya', price: 36000, photo: '31' },
  { id: 'sop-daging-sapi',    cat: 'soup', name: 'Sop Daging Sapi', price: 45000 },
  { id: 'sop-tulang-sapi',    cat: 'soup', name: 'Sop Tulang Sapi', price: 45000 },
  { id: 'sop-ayam-kampung',   cat: 'soup', name: 'Sop Ayam Kampung', price: 55000 },
  { id: 'sop-buntut-kuah',    cat: 'soup', name: 'Sop Buntut Kuah', price: 80000 },
  { id: 'sop-buntut-goreng',  cat: 'soup', name: 'Sop Buntut Goreng Cabe Ijo', price: 80000, photo: '14' },
  { id: 'soto-ayam-nyonya',   cat: 'soup', name: 'Soto Ayam Nyonya', price: 36000, photo: '42', desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-kari-nyonya',   cat: 'soup', name: 'Soto Kari Nyonya', price: 38000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-daging-sapi',   cat: 'soup', name: 'Soto Daging Sapi', price: 45000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'soto-ayam-kampung',  cat: 'soup', name: 'Soto Ayam Kampung', price: 55000, desc: 'Pilihan kuah susu atau bening' },
  { id: 'pindang-tulang-sapi',cat: 'soup', name: 'Pindang Tulang Sapi', price: 45000, photo: '58' },
  { id: 'pindang-ayam-kampung', cat: 'soup', name: 'Pindang Ayam Kampung', price: 55000 },
  { id: 'iga-bakar',          cat: 'soup', name: 'Iga Bakar', price: 55000 },
  { id: 'mun-tahu-ayam',      cat: 'soup', name: 'Mun Tahu Ayam', price: 30000 },
  { id: 'mapo-tahu-ayam',     cat: 'soup', name: 'Mapo Tahu Ayam', price: 35000 },

  /* ---------------- NASI ---------------- */
  { id: 'nasi-ayam-gepuk',        cat: 'nasi', name: 'Nasi Ayam Gepuk', price: 30000, photo: '51' },
  { id: 'nasi-ayam-gepuk-kampung',cat: 'nasi', name: 'Nasi Ayam Gepuk Kampung', price: 48000 },
  { id: 'nasi-ayam-karage',       cat: 'nasi', name: 'Nasi Ayam Karage', price: 38000 },
  { id: 'nasi-ayam-teriyaki',     cat: 'nasi', name: 'Nasi Ayam Teriyaki', price: 38000 },
  { id: 'nasi-ayam-mentega',      cat: 'nasi', name: 'Nasi Ayam Mentega', price: 38000 },
  { id: 'nasi-ayam-saos-lemon',   cat: 'nasi', name: 'Nasi Ayam Saos Lemon', price: 38000 },
  { id: 'nasi-ayam-sambal-matah', cat: 'nasi', name: 'Nasi Ayam Sambal Matah', price: 38000 },
  { id: 'nasi-ayam-saos-padang',  cat: 'nasi', name: 'Nasi Ayam Saos Padang', price: 38000 },
  { id: 'nasi-ayam-asam-manis',   cat: 'nasi', name: 'Nasi Ayam Asam Manis', price: 38000 },
  { id: 'nasi-ayam-salted-egg',   cat: 'nasi', name: 'Nasi Ayam Salted Egg', price: 38000 },
  { id: 'nasi-ayam-korean-spicy', cat: 'nasi', name: 'Nasi Ayam Korean Spicy', price: 38000 },
  { id: 'nasi-chicken-katsu',     cat: 'nasi', name: 'Nasi Chicken Katsu', price: 38000 },
  { id: 'nasi-chicken-hainan',    cat: 'nasi', name: 'Nasi Chicken Hainan', price: 38000 },
  { id: 'nasi-katsu-curry',       cat: 'nasi', name: 'Nasi Chicken Katsu Curry', price: 40000 },
  { id: 'nasi-dori-asam-manis',   cat: 'nasi', name: 'Nasi Dori Asam Manis', price: 38000, photo: '33' },
  { id: 'nasi-dori-saos-padang',  cat: 'nasi', name: 'Nasi Dori Saos Padang', price: 38000 },
  { id: 'nasi-dori-sambal-matah', cat: 'nasi', name: 'Nasi Dori Sambal Matah', price: 38000, photo: '01', tag: 'Favorit' },
  { id: 'nasi-dori-saos-lemon',   cat: 'nasi', name: 'Nasi Dori Saos Lemon', price: 38000 },
  { id: 'nasi-dori-salted-egg',   cat: 'nasi', name: 'Nasi Dori Salted Egg', price: 38000 },
  { id: 'nasi-bakar-teri',        cat: 'nasi', name: 'Nasi Bakar Teri', price: 38000, photo: '25' },
  { id: 'nasi-bakar-cumi',        cat: 'nasi', name: 'Nasi Bakar Cumi', price: 40000 },
  { id: 'nasi-siram-teriyaki',    cat: 'nasi', name: 'Nasi Siram Teriyaki', price: 38000 },
  { id: 'nasi-sapi-lada-hitam',   cat: 'nasi', name: 'Nasi Sapi Lada Hitam', price: 45000 },
  { id: 'nasi-sapi-barbeque',     cat: 'nasi', name: 'Nasi Sapi Barbeque', price: 45000 },
  { id: 'nasi-siram-sapi',        cat: 'nasi', name: 'Nasi Siram Sapi', price: 45000 },

  /* ---------------- MIE ---------------- */
  { id: 'mie-tumis-jawa',     cat: 'mie', name: 'Mie Tumis Jawa', price: 32000 },
  { id: 'mie-goreng-jadoel',  cat: 'mie', name: 'Mie Goreng Jadoel', price: 32000, photo: '47', tag: 'Favorit' },
  { id: 'mie-goreng-seafood', cat: 'mie', name: 'Mie Goreng Seafood', price: 38000 },
  { id: 'mie-goreng-siram-sapi', cat: 'mie', name: 'Mie Goreng Siram Sapi', price: 48000 },
  { id: 'bihun-goreng-jadoel',cat: 'mie', name: 'Bihun Goreng Jadoel', price: 32000 },
  { id: 'bihun-goreng-seafood', cat: 'mie', name: 'Bihun Goreng Seafood', price: 38000 },
  { id: 'bihun-ayam-curry',   cat: 'mie', name: 'Bihun Ayam Curry', price: 40000, photo: '10' },
  { id: 'bihun-goreng-nyonya',cat: 'mie', name: 'Bihun Goreng Nyonya', price: 45000 },
  { id: 'mie-ayam-curry',     cat: 'mie', name: 'Mie Ayam Curry', price: 40000 },
  { id: 'mie-goreng-nyonya',  cat: 'mie', name: 'Mie Goreng Nyonya', price: 45000 },
  { id: 'kwetiaw-ayam-cincang', cat: 'mie', name: 'Kwetiaw Ayam Cincang', price: 28000 },
  { id: 'kwetiaw-ayam-suwir', cat: 'mie', name: 'Kwetiaw Ayam Kampung Suwir', price: 30000 },
  { id: 'kwetiaw-goreng-ayam',cat: 'mie', name: 'Kwetiaw Goreng Ayam', price: 35000 },
  { id: 'kwetiaw-singapore',  cat: 'mie', name: 'Kwetiaw Singapore', price: 35000 },
  { id: 'kwetiaw-goreng-seafood', cat: 'mie', name: 'Kwetiaw Goreng Seafood', price: 40000 },
  { id: 'kwetiaw-goreng-sapi',cat: 'mie', name: 'Kwetiaw Goreng Sapi', price: 48000 },

  /* ---------------- NASI GORENG ---------------- */
  { id: 'nasgor-merah-jadoel',cat: 'nasgor', name: 'Nasi Goreng Merah Jadoel', price: 30000 },
  { id: 'nasgor-jadoel',      cat: 'nasgor', name: 'Nasi Goreng Jadoel', price: 30000, tag: 'Bestseller' },
  { id: 'nasgor-cabe-ijo',    cat: 'nasgor', name: 'Nasi Goreng Cabe Ijo', price: 35000 },
  { id: 'nasgor-ikan-asin',   cat: 'nasgor', name: 'Nasi Goreng Ikan Asin', price: 38000 },
  { id: 'nasgor-pete',        cat: 'nasgor', name: 'Nasi Goreng Pete', price: 38000 },
  { id: 'nasgor-seafood',     cat: 'nasgor', name: 'Nasi Goreng Seafood', price: 38000 },
  { id: 'nasgor-nyonya-kampung', cat: 'nasgor', name: 'Nasi Goreng Nyonya Kampung', price: 55000 },
  { id: 'nasgor-hongkong',    cat: 'nasgor', name: 'Nasi Goreng Hongkong', price: 38000 },
  { id: 'nasgor-merah-spesial', cat: 'nasgor', name: 'Nasi Goreng Merah Spesial', price: 48000 },
  { id: 'nasgor-nyonya',      cat: 'nasgor', name: 'Nasi Goreng Nyonya', price: 45000 },
  { id: 'nasgor-yang-zhou',   cat: 'nasgor', name: 'Nasi Goreng Yang Zhou', price: 38000 },
  { id: 'nasgor-ikan-teri',   cat: 'nasgor', name: 'Nasi Goreng Ikan Teri', price: 35000 },

  /* ---------------- KOPI ---------------- */
  { id: 'kopi-jadoel',        cat: 'coffee', name: 'Kopi Jadoel', price: 10000, photo: '11', tag: 'Signature', desc: 'Kopi hitam ala Palembang' },
  { id: 'kopi-susu',          cat: 'coffee', name: 'Kopi Susu', price: 14000, photo: '54' },
  { id: 'kopi-gula-aren',     cat: 'coffee', name: 'Kopi Gula Aren', price: 16000 },
  { id: 'kopi-cincau-susu',   cat: 'coffee', name: 'Kopi Cincau Susu', price: 28000 },
  { id: 'kopi-janji-hati',    cat: 'coffee', name: 'Kopi Janji Hati', price: 26000, photo: '08', tag: 'Bestseller' },
  { id: 'vietnam-drip',       cat: 'coffee', name: 'Vietnam Drip', price: 25000, photo: '28' },

  /* ---------------- MODERN COFFEE ---------------- */
  { id: 'espresso',           cat: 'modern', name: 'Espresso', price: 18000 },
  { id: 'americano',          cat: 'modern', name: 'Americano', price: 20000 },
  { id: 'cappucino',          cat: 'modern', name: 'Cappucino', price: 25000 },
  { id: 'coffee-latte',       cat: 'modern', name: 'Coffee Latte', price: 26000 },
  { id: 'caramel-latte',      cat: 'modern', name: 'Caramel Latte', price: 30000 },
  { id: 'hazelnut-latte',     cat: 'modern', name: 'Hazelnut Latte', price: 30000 },
  { id: 'vanilla-latte',      cat: 'modern', name: 'Vanilla Latte', price: 28000 },
  { id: 'taro-latte',         cat: 'modern', name: 'Taro Latte', price: 28000 },
  { id: 'kojo-latte',         cat: 'modern', name: 'Kojo Latte', price: 28000 },
  { id: 'blue-salted-latte',  cat: 'modern', name: 'Blue Salted Latte', price: 28000 },
  { id: 'matcha-latte',       cat: 'modern', name: 'Matcha Latte', price: 28000 },
  { id: 'choco-latte',        cat: 'modern', name: 'Choco Latte', price: 28000 },
  { id: 'caramel-macchiato',  cat: 'modern', name: 'Caramel Latte Macchiato', price: 35000 },
  { id: 'blue-salted-macchiato', cat: 'modern', name: 'Blue Salted Latte Macchiato', price: 35000 },
  { id: 'klepon-creamy',      cat: 'modern', name: 'Klepon Creamy Cheese', price: 35000 },
  { id: 'oreo-creamy',        cat: 'modern', name: 'Oreo Creamy Cheese', price: 36000 },
  { id: 'caramel-creamy',     cat: 'modern', name: 'Caramel Creamy Cheese', price: 36000 },
  { id: 'taro-creamy',        cat: 'modern', name: 'Taro Creamy Cheese', price: 32000 },
  { id: 'matcha-creamy',      cat: 'modern', name: 'Matcha Creamy Cheese', price: 35000 },
  { id: 'strawberry-matcha-creamy', cat: 'modern', name: 'Strawberry Matcha Creamy', price: 36000 },

  /* ---------------- TEH ---------------- */
  { id: 'teh-tarik',          cat: 'tea', name: 'Teh Tarik', price: 20000 },
  { id: 'teh-tarik-chai',     cat: 'tea', name: 'Teh Tarik "Chai Masala"', price: 25000 },
  { id: 'teh-tarik-cincau',   cat: 'tea', name: 'Teh Tarik Cincau', price: 25000 },
  { id: 'bandrek-jahe',       cat: 'tea', name: 'Bandrek Jahe', price: 20000 },
  { id: 'bandrek-susu',       cat: 'tea', name: 'Bandrek Susu', price: 23000 },
  { id: 'bandrek-telor',      cat: 'tea', name: 'Bandrek Telor Kampung', price: 28000 },
  { id: 'teh-tawar',          cat: 'tea', name: 'Teh Tawar', price: 8000 },
  { id: 'teh-manis',          cat: 'tea', name: 'Teh Manis', price: 10000 },
  { id: 'dilmah-chinese',     cat: 'tea', name: 'Chinese Tea', price: 30000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-english',     cat: 'tea', name: 'English Breakfast', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-chamomile',   cat: 'tea', name: 'Chamomile', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-peppermint',  cat: 'tea', name: 'Peppermint', price: 28000, desc: 'Dilmah — free refill 1x' },
  { id: 'dilmah-green',       cat: 'tea', name: 'Green Tea', price: 28000, desc: 'Dilmah — free refill 1x' },

  /* ---------------- ICE CREAM ---------------- */
  { id: 'affogato',           cat: 'icecream', name: 'Affogato Coffee', price: 28000, photo: '29', focus: '50% 62%' },
  { id: 'avocado-float',      cat: 'icecream', name: 'Avocado Float', price: 36000 },
  { id: 'avocado-float-coffee', cat: 'icecream', name: 'Avocado Float Coffee', price: 38000 },
  { id: 'avocado-vanila',     cat: 'icecream', name: 'Avocado Vanila Ice Cream', price: 38000 },
  { id: 'oreo-float',         cat: 'icecream', name: 'Oreo Float', price: 38000 },
  { id: 'strawberry-float',   cat: 'icecream', name: 'Strawberry Float', price: 35000 },
  { id: 'mango-float',        cat: 'icecream', name: 'Mango Float', price: 35000 },
  { id: 'chocolate-float',    cat: 'icecream', name: 'Chocolate Float', price: 35000 },

  /* ---------------- SODA ---------------- */
  { id: 'magic-purple',       cat: 'soda', name: 'Magic Purple', price: 30000 },
  { id: 'morning-sunrise',    cat: 'soda', name: 'Morning Sunrise', price: 30000 },
  { id: 'pink-sunshine',      cat: 'soda', name: 'Pink Sunshine', price: 30000 },
  { id: 'mint-grass-mojito',  cat: 'soda', name: 'Mint Grass Mojito', price: 30000 },
  { id: 'love-poison',        cat: 'soda', name: 'Love Poison', price: 30000 },
  { id: 'blue-ocean',         cat: 'soda', name: 'Blue Ocean', price: 30000 },
  { id: 'yellow-cream-lime',  cat: 'soda', name: 'Yellow Cream Lime', price: 30000 },
  { id: 'mango-yuzu-coco',    cat: 'soda', name: 'Mango Yuzu Coco', price: 30000 },
  { id: 'pineapple-conlada',  cat: 'soda', name: 'Pineapple Conlada', price: 30000 },
  { id: 'lemon-tea-squash',   cat: 'soda', name: 'Lemon Tea Squash', price: 60000, desc: 'Sharing portion' },
  { id: 'green-tea-squash',   cat: 'soda', name: 'Green Tea Squash', price: 65000, desc: 'Sharing portion' },

  /* ---------------- JUS ---------------- */
  { id: 'jus-nanas',          cat: 'juice', name: 'Jus Nanas', price: 28000 },
  { id: 'jus-strawberry',     cat: 'juice', name: 'Jus Strawberry', price: 30000 },
  { id: 'jus-semangka',       cat: 'juice', name: 'Jus Semangka', price: 28000 },
  { id: 'jus-sirsak',         cat: 'juice', name: 'Jus Sirsak', price: 30000 },
  { id: 'jus-melon',          cat: 'juice', name: 'Jus Melon', price: 28000 },
  { id: 'jus-mangga',         cat: 'juice', name: 'Jus Mangga', price: 35000 },
  { id: 'jus-avocado',        cat: 'juice', name: 'Jus Avocado', price: 35000 },
  { id: 'jus-mango-berry',    cat: 'juice', name: 'Jus Mango Berry', price: 35000, desc: 'Strawberry + mangga' },
  { id: 'jus-mango-pineapple',cat: 'juice', name: 'Jus Mango Pineapple', price: 35000, desc: 'Nanas + mangga' },
  { id: 'jus-white-mango',    cat: 'juice', name: 'Jus White Mango', price: 35000, desc: 'Sirsak + mangga' },

  /* ---------------- NON-COFFEE ---------------- */
  { id: 'milo',               cat: 'noncoffee', name: 'Milo', price: 28000 },
  { id: 'milo-cincau',        cat: 'noncoffee', name: 'Milo Cincau', price: 35000 },
  { id: 'milo-dinosaurus',    cat: 'noncoffee', name: 'Milo Dinosaurus', price: 36000 },
  { id: 'ginger-tea',         cat: 'noncoffee', name: 'Ginger Tea', price: 25000 },
  { id: 'honey-lemon-tea',    cat: 'noncoffee', name: 'Honey Lemon Tea', price: 26000 },
  { id: 'honey-ginger-lemonade', cat: 'noncoffee', name: 'Honey Ginger Lemonade', price: 30000 },
  { id: 'lychee-ice-tea',     cat: 'noncoffee', name: 'Lychee Ice Tea', price: 30000 },
  { id: 'lemon-tea',          cat: 'noncoffee', name: 'Lemon Tea', price: 20000 },
  { id: 'honey-lemonade',     cat: 'noncoffee', name: 'Honey Lemonade', price: 26000 },
  { id: 'jeruk-nipis',        cat: 'noncoffee', name: 'Jeruk Nipis', price: 26000 },
  { id: 'jeruk-kunci',        cat: 'noncoffee', name: 'Jeruk Kunci', price: 26000 },
  { id: 'jeruk-manis',        cat: 'noncoffee', name: 'Jeruk Manis', price: 26000 },
  { id: 'jeruk-murni',        cat: 'noncoffee', name: 'Jeruk Murni', price: 38000 },
  { id: 'jeruk-nipis-asamboy',cat: 'noncoffee', name: 'Jeruk Nipis Asamboy', price: 28000 },
  { id: 'jeruk-kunci-asamboy',cat: 'noncoffee', name: 'Jeruk Kunci Asamboy', price: 28000 },
  { id: 'jeruk-manis-asamboy',cat: 'noncoffee', name: 'Jeruk Manis Asamboy', price: 28000 },

  /* ---------------- MAGNUM ---------------- */
  { id: 'magnum-mango-yogurt',cat: 'magnum', name: 'Magnum Mango Yogurt', price: 53000, photo: '44' },
  { id: 'magnum-berry-yogurt',cat: 'magnum', name: 'Magnum Berry Yogurt', price: 53000 },
  { id: 'magnum-choco-cheese',cat: 'magnum', name: 'Magnum Choco Cheese', price: 53000, photo: '59' },
  { id: 'magnum-oreo-cheese', cat: 'magnum', name: 'Magnum Oreo Cheese', price: 53000 },
  { id: 'magnum-matcha-cheese', cat: 'magnum', name: 'Magnum Matcha Cheese', price: 53000 },
];

/* Shown as large photo cards at the top of the menu. */
window.CJ_FEATURED = [
  'kopi-jadoel', 'mie-celor', 'roti-bakar-abon',
  'sate-ayam-kacang', 'nasi-dori-sambal-matah', 'soto-ayam-nyonya',
];
